export enum CargoEnum {
  ADMIN = 'ADMIN',
  PCP = 'PCP',
  USER = 'USER',
  CATERPILLAR_USER = 'CATERPILLAR_USER',
  LIDER_SOLDA = 'LIDER_SOLDA',
  LIDER_MONTAGEM = 'LIDER_MONTAGEM',
  LIDER_LASER = 'LIDER_LASER',
  LIDER_QUALIDADE = 'LIDER_QUALIDADE',
  DIRETOR = 'DIRETOR',
}
