export enum CargoEnum {
  ADMIN = 'ADMIN',
  PCP = 'PCP',
  USER = 'USER',
  CATERPILLAR_USER = 'CATERPILLAR_USER',
  //
  LIDER_LASER = 'LIDER_LASER',
  LIDER_SOLDA = 'LIDER_SOLDA',
  LIDER_MONTAGEM = 'LIDER_MONTAGEM',
  LIDER_QUALIDADE = 'LIDER_QUALIDADE',
  LIDER_PROCESSOS = 'LIDER_PROCESSOS',
  DIRETOR = 'DIRETOR',
  LIDER_PCP='LIDER_PCP',
  //
  ADMIN_POWERBI='ADMIN_POWERBI',
  ADMIN_POWERBI_VIEW='FADMIN_POWERBI_VIEWI'
}
