import { Module } from '@nestjs/common';
import { FabricaServiceModule } from './FabricaService.module';
import { UserServiceModule } from '../user/UserService.module';

import {
  DesplanejarPedidoUseCase,
  ConsultarDatasPlanejadasUseCase,
  AtualizarPlanejamentoUseCase,
  ConsultarFabricaUseCase,
  ConsultarPlanejamentosUseCase,
  ConsultarPedidosPlanejadosUseCase,
  ConsutlarFabricaPrincipalAtualUseCase,
  ConsutlarFabricasDoUsuarioUseCase,
  CriarNovaFabricaPrincipalUseCase,
  HandleStartUpBuildFabricaUseCase,
  RequestFabricaForkUseCase,
  PlanejarPedidoUseCase,
  MergeFabricaUseCase,
  RequestFabricaMergeUseCase,
  ConsultaMergeRequestUseCase,
  AdicionarPlanejamentoManualUseCase,
  ResetaFabricaUseCase,
  RemoverPlanejamentoUseCase,
  DeletarFabricaUseCase,
  ConsultarHistoricoFabricaUseCase,
  SincronizarFabricaPrivadaUseCase,
} from './application';
import { ItemServiceModule } from './ItemService.module';
import { PedidoServiceModule } from './PedidoService.module';
import { PlanejamentoServiceModule } from './PlanejamentoService.module';

@Module({
  imports: [
    ItemServiceModule,
    PedidoServiceModule,
    UserServiceModule,
    FabricaServiceModule,
    PlanejamentoServiceModule,
    PedidoServiceModule,
  ],
  providers: [
    DesplanejarPedidoUseCase,
    AtualizarPlanejamentoUseCase,
    HandleStartUpBuildFabricaUseCase,
    AdicionarPlanejamentoManualUseCase,
    RequestFabricaMergeUseCase,
    ConsultaMergeRequestUseCase,
    ConsultarDatasPlanejadasUseCase,
    CriarNovaFabricaPrincipalUseCase,
    PlanejarPedidoUseCase,
    ConsutlarFabricaPrincipalAtualUseCase,
    SincronizarFabricaPrivadaUseCase,
    RequestFabricaForkUseCase,
    ConsutlarFabricasDoUsuarioUseCase,
    ConsultarHistoricoFabricaUseCase,
    ConsultarPlanejamentosUseCase,
    ConsultarFabricaUseCase,
    ConsultarPedidosPlanejadosUseCase,
    ResetaFabricaUseCase,
    MergeFabricaUseCase,
    ConsultarPlanejamentosUseCase,
    DeletarFabricaUseCase,
    RemoverPlanejamentoUseCase,
  ],
  exports: [
    ConsultarPlanejamentosUseCase,
    RequestFabricaMergeUseCase,
    DesplanejarPedidoUseCase,
    RemoverPlanejamentoUseCase,
    DeletarFabricaUseCase,
    MergeFabricaUseCase,
    ResetaFabricaUseCase,
    ConsultarFabricaUseCase,
    AtualizarPlanejamentoUseCase,
    ConsultarHistoricoFabricaUseCase,
    ConsutlarFabricasDoUsuarioUseCase,
    ConsultarPlanejamentosUseCase,
    ConsultarPedidosPlanejadosUseCase,
    RequestFabricaForkUseCase,
    AdicionarPlanejamentoManualUseCase,
    ConsutlarFabricaPrincipalAtualUseCase,
    CriarNovaFabricaPrincipalUseCase,
    ConsultaMergeRequestUseCase,
    ConsultarDatasPlanejadasUseCase,
    HandleStartUpBuildFabricaUseCase,
    SincronizarFabricaPrivadaUseCase,
    PlanejarPedidoUseCase,
  ],
})
export class FabricaModule {}
